//
//  ZZBlockProtocols.swift
//  ZamZamDemo
//
//  Created Daniil Pendikov on 10/11/2018.
//  Copyright © 2018 Daniil Pendikov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//Protocols for VIPER

//MARK: Wireframe -
protocol ZZBlockWireframeProtocol: class {
    
}
//MARK: Presenter -
protocol ZZBlockPresenterProtocol: class {
    func start()
    func update(block: ZZBlock)
}

//MARK: Interactor -
protocol ZZBlockInteractorProtocol: class {
    
    var presenter: ZZBlockPresenterProtocol?  { get set }
}

//MARK: View -
protocol ZZBlockViewProtocol: class {
    
    var presenter: ZZBlockPresenterProtocol?  { get set }
    func update(rows: [String], transactions: [String])
}
