//
//  ZZBlockInteractor.swift
//  ZamZamDemo
//
//  Created Daniil Pendikov on 10/11/2018.
//  Copyright © 2018 Daniil Pendikov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ZZBlockInteractor: ZZBlockInteractorProtocol {

    weak var presenter: ZZBlockPresenterProtocol?
    weak var blockchain: ZZBlockchainService?
    
}
