//
//  ZZBlockViewController.swift
//  ZamZamDemo
//
//  Created Daniil Pendikov on 10/11/2018.
//  Copyright © 2018 Daniil Pendikov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ZZBlockViewController: UIViewController, ZZBlockViewProtocol {

	var presenter: ZZBlockPresenterProtocol?
    var rows: [String] = []
    var transactions: [String] = []
    let cellIdentifier = "cell"

    @IBOutlet weak var tableView: UITableView!
    override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "Block"
        self.configureTableView()
        self.presenter?.start()
    }
    
    private func configureTableView() {
        self.tableView.allowsSelection = false
        self.tableView.register(UITableViewCell.self,
                                forCellReuseIdentifier: self.cellIdentifier)
        self.tableView.dataSource = self
        self.tableView.delegate = self
    }
    
    func update(rows: [String], transactions: [String]) {
        self.rows = rows
        self.transactions = transactions
        self.tableView.reloadData()
    }

}

extension ZZBlockViewController: UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        if section == 1 {
            return "Transactions:"
        }
        return nil
    }
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return 2
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if section == 0 {
            return self.rows.count
        } else {
            return self.transactions.count
        }
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: self.cellIdentifier,
                                                 for: indexPath)
        if indexPath.section == 0 {
            cell.textLabel?.text = self.rows[indexPath.row]
        } else {
            cell.textLabel?.text = self.transactions[indexPath.row]
        }
        return cell
    }
}

extension ZZBlockViewController: UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        
        
    }
    
}
