//
//  ZZBlockRouter.swift
//  ZamZamDemo
//
//  Created Daniil Pendikov on 10/11/2018.
//  Copyright © 2018 Daniil Pendikov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ZZBlockRouter: ZZBlockWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(block: ZZBlock, blockchain: ZZBlockchainService) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ZZBlockViewController(nibName: nil, bundle: nil)
        let interactor = ZZBlockInteractor()
        let router = ZZBlockRouter()
        let presenter = ZZBlockPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        presenter.block = block
        interactor.blockchain = blockchain
        
        return view
    }
}
