//
//  ZZTransactionsViewController.swift
//  ZamZamDemo
//
//  Created Daniil Pendikov on 09/11/2018.
//  Copyright © 2018 Daniil Pendikov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ZZTransactionsViewController: UIViewController, ZZTransactionsViewProtocol {

	var presenter: ZZTransactionsPresenterProtocol?
    
    @IBOutlet weak var tableView: UITableView!
    private var transactions: [ZZTransaction] = []
    let cellIdentifier = "cell"
    
    var isLoading: Bool = false {
        didSet {
            if self.isLoading {
                ZZActivityIndicator.addToView(self.view)
            } else {
                ZZActivityIndicator.removeFromView(self.view)
            }
        }
    }
    
    convenience init() {
        self.init(nibName: String(describing: type(of: self)), bundle: nil)
        self.title = "Transactions"
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        self.configureTableView()
        self.presenter?.start()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        if let indexPath = self.tableView.indexPathForSelectedRow {
            self.tableView.deselectRow(at: indexPath, animated: true)
        }
    }
    
    private func configureTableView() {
        self.tableView.register(UITableViewCell.self,
                                forCellReuseIdentifier: self.cellIdentifier)
        self.tableView.dataSource = self
        self.tableView.delegate = self
    }
    
    func add(transaction: ZZTransaction) {
        self.transactions.insert(transaction, at: 0)
        self.tableView.insertRows(at: [IndexPath(row: 0, section: 0)], with: .automatic)
        self.updateTitle()
    }
    
    func removeLastAndAdd(transaction: ZZTransaction) {
        self.transactions.removeLast()
        self.transactions.insert(transaction, at: 0)
        self.tableView.beginUpdates()
        self.tableView.insertRows(at: [IndexPath(row: 0, section: 0)], with: .automatic)
        self.tableView.deleteRows(at: [IndexPath(row: self.tableView.numberOfRows(inSection: 0)-1, section: 0)], with: .automatic)
        self.tableView.endUpdates()
        self.updateTitle()
    }
    
    func reloadAll(transactions: [ZZTransaction]) {
        self.transactions = transactions
        self.tableView.reloadData()
        self.updateTitle()
    }
    
    func updateTitle() {
        self.navigationItem.title = "Showing last \(self.transactions.count) transactions"
    }

}

extension ZZTransactionsViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.transactions.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: self.cellIdentifier,
                                                 for: indexPath)
        cell.textLabel?.text = self.transactions[indexPath.row].txid
        return cell
    }
}

extension ZZTransactionsViewController: UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let trans = self.transactions[indexPath.row]
        self.presenter?.show(transaction: trans)
    }
    
}


