//
//  ZZTransactionsInteractor.swift
//  ZamZamDemo
//
//  Created Daniil Pendikov on 09/11/2018.
//  Copyright © 2018 Daniil Pendikov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ZZTransactionsInteractor: ZZTransactionsInteractorProtocol {

    weak var presenter: ZZTransactionsPresenterProtocol?
    
    weak var blockchain: ZZBlockchainService?
    
    func start() {
        guard let blockchain = self.blockchain else {
            log.error("ZZTransactionsInteractor blockchain must be set")
            return
        }
        blockchain.onTransaction = { transaction in
            if blockchain.transactions.count < ZZConfig.maxTransactions {
                self.presenter?.add(transaction: transaction)
            } else {
                self.presenter?.removeLastAndAdd(transaction: transaction)
            }
        }
    }
    
    func allTransactions() -> [ZZTransaction] {
        return self.blockchain?.transactions ?? []
    }
    
}
