//
//  ZZBlocksInteractor.swift
//  ZamZamDemo
//
//  Created Daniil Pendikov on 10/11/2018.
//  Copyright © 2018 Daniil Pendikov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ZZBlocksInteractor: ZZBlocksInteractorProtocol {

    weak var presenter: ZZBlocksPresenterProtocol?
    weak var blockchain: ZZBlockchainService?
    
    func start() {
        self.blockchain?.onBlock = { block in
            self.presenter?.add(blocks: [block])
        }
    }
    
}
