//
//  ZZBlocksRouter.swift
//  ZamZamDemo
//
//  Created Daniil Pendikov on 10/11/2018.
//  Copyright © 2018 Daniil Pendikov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ZZBlocksRouter: ZZBlocksWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(blockchain: ZZBlockchainService) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ZZBlocksViewController()
        let interactor = ZZBlocksInteractor()
        let router = ZZBlocksRouter()
        let presenter = ZZBlocksPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        interactor.blockchain = blockchain
        
        return view
    }
    
    func show(block: ZZBlock, blockchain: ZZBlockchainService) {
        let controller = ZZBlockRouter.createModule(block: block, blockchain: blockchain)
        self.viewController?.navigationController?.pushViewController(controller, animated: true)
    }
}
