//
//  ZZBlocksProtocols.swift
//  ZamZamDemo
//
//  Created Daniil Pendikov on 10/11/2018.
//  Copyright © 2018 Daniil Pendikov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//Protocols for VIPER

//MARK: Wireframe -
protocol ZZBlocksWireframeProtocol: class {
    func show(block: ZZBlock, blockchain: ZZBlockchainService)
}
//MARK: Presenter -
protocol ZZBlocksPresenterProtocol: class {
    func start()
    func add(blocks: [ZZBlock])
    func show(block: ZZBlock)
}

//MARK: Interactor -
protocol ZZBlocksInteractorProtocol: class {
    
    var presenter: ZZBlocksPresenterProtocol?  { get set }
    
    var blockchain: ZZBlockchainService? { get set }
    func start()
}

//MARK: View -
protocol ZZBlocksViewProtocol: class {
    
    var presenter: ZZBlocksPresenterProtocol?  { get set }
    
    var isLoading: Bool { get set }
    func add(blocks: [ZZBlock])
}
