//
//  ZZTransactionInteractor.swift
//  ZamZamDemo
//
//  Created Daniil Pendikov on 10/11/2018.
//  Copyright © 2018 Daniil Pendikov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ZZTransactionInteractor: ZZTransactionInteractorProtocol {

    weak var presenter: ZZTransactionPresenterProtocol?
    
    weak var blockchain: ZZBlockchainService?
    
}
