//
//  ZZTransactionProtocols.swift
//  ZamZamDemo
//
//  Created Daniil Pendikov on 10/11/2018.
//  Copyright © 2018 Daniil Pendikov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//Protocols for VIPER

//MARK: Wireframe -
protocol ZZTransactionWireframeProtocol: class {
    
}
//MARK: Presenter -
protocol ZZTransactionPresenterProtocol: class {
    var transaction: ZZTransaction? { get set }
    func start()
}

//MARK: Interactor -
protocol ZZTransactionInteractorProtocol: class {
    
    var presenter: ZZTransactionPresenterProtocol?  { get set }
}

//MARK: View -
protocol ZZTransactionViewProtocol: class {
    
    var presenter: ZZTransactionPresenterProtocol?  { get set }
    
    func update(rows: [String])
}
