//
//  ZZTransactionRouter.swift
//  ZamZamDemo
//
//  Created Daniil Pendikov on 10/11/2018.
//  Copyright © 2018 Daniil Pendikov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ZZTransactionRouter: ZZTransactionWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(transaction: ZZTransaction,
                             blockchain: ZZBlockchainService) -> UIViewController {
        let view = ZZTransactionViewController(nibName: nil, bundle: nil)
        let interactor = ZZTransactionInteractor()
        let router = ZZTransactionRouter()
        let presenter = ZZTransactionPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        interactor.blockchain = blockchain
        presenter.transaction = transaction
        
        return view
    }

}
