//
//  ZZTransactionViewController.swift
//  ZamZamDemo
//
//  Created Daniil Pendikov on 10/11/2018.
//  Copyright © 2018 Daniil Pendikov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ZZTransactionViewController: UIViewController, ZZTransactionViewProtocol {

	var presenter: ZZTransactionPresenterProtocol?
    
    @IBOutlet weak var tableView: UITableView!
    var rows: [String] = []
    let cellIdentifier = "cell"

    override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "Transaction"
        self.configureTableView()
        self.presenter?.start()
    }
    
    private func configureTableView() {
        self.tableView.allowsSelection = false
        self.tableView.register(UITableViewCell.self,
                                forCellReuseIdentifier: self.cellIdentifier)
        self.tableView.dataSource = self
    }
    
    func update(rows: [String]) {
        self.rows = rows
        self.tableView.reloadData()
    }
    
}

extension ZZTransactionViewController: UITableViewDataSource {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.rows.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: self.cellIdentifier,
                                                 for: indexPath)
        cell.textLabel?.text = self.rows[indexPath.row]
        return cell
    }
}
